[turbofan]: Add exception when receiver does not have `Symbol.iterator` in the `ReduceJSGetIterator` reduction
If the result of loading `Symbol.iterator` from the receiver is
undefined, the JSCall (generated by `ReduceJSGetIterator`) will always
throw with `TypeError: undefined is not a function`, instead of the
invalid iterator error which is the expected one.

Throwing an exception using the `ThrowIteratorError` runtime function
when the iterator is not present in the receiver will make the
behavior consistent with the non-optimized result.

Bug: v8:13517
Change-Id: Idf82431e2cb29e5e9c527e5a5704f9f8cf594fc8
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4407872
Auto-Submit: Juan José <soyjuanarbol@gmail.com>
Reviewed-by: Nico Hartmann <nicohartmann@chromium.org>
Commit-Queue: Nico Hartmann <nicohartmann@chromium.org>
Cr-Commit-Position: refs/heads/main@{#87168}